version: '3.7'

services:
  currency-exchange:
    image: in28min/mmv3-currency-exchange-service:0.0.12-SNAPSHOT
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network


networks:
  currency-network:
