version: '3.7'

services:
  currency-exchange:
    # image: daedalus1215/currency-exchange-service:latest
    build:
      context: .
      dockerfile: Dockerfile.exchange-server
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans

  currency-conversion:
    build: 
      context: .
      dockerfile: Dockerfile.conversion
    # image: in28min/mmv2-currency-conversion-service:0.0.12-SNAPSHOT
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka  
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api-gateway
    ports: 
      - "8765:8765"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network 
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka  
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans
    
  naming-server:
    build: 
      context: .
      dockerfile: Dockerfile.naming-server
    # image: daedalus1215/currency-naming-service:latest
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up

networks:
  currency-network:
