version: '3.7'

services:
  currency-exchange:
    # image: daedalus1215/currency-exchange-service:latest
    build:
      context: .
      dockerfile: Dockerfile.exchange-server
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka

  currency-conversion:
    build: 
      context: .
      dockerfile: Dockerfile.conversion
    # image: in28min/mmv2-currency-conversion-service:0.0.12-SNAPSHOT
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka  
      

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api-gateway
    ports: 
      - "8765:8765"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network 
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka  
    
  naming-server:
    build: 
      context: .
      dockerfile: Dockerfile.naming-server
    # image: daedalus1215/currency-naming-service:latest
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network

networks:
  currency-network:
